name: Team-13 CI

on: [push, pull_request]

jobs:
  val_tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
#    - name: configure
#      run: ./configure
    - name: Install cunit
      run: sudo apt-get install libcunit1-dev libcunit1-doc libcunit1
    - name: make compile
      run: make compile
    - name: make val_tests
      run: make val_tests
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
