name: Team-13 CI

on: [pull_request]

jobs:
  val_tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update packages
      run: sudo apt-get update
    - name: Install cunit & valgrind
      run: sudo apt-get install libcunit1-dev libcunit1-doc libcunit1 valgrind
    - name: make compile
      run: make compile
    - name: make test
      run: make test
    - name: make memtest
      run: make memtest
    - name: make inlupp_unit_tests
      run: make inlupp_unit_tests
    - name: make val_inlupp_unit_tests
      run: make val_inlupp_unit_tests

